"""Tests for the opt-in MQTT capture recorder.

The CaptureRecorder writes JSONL traces of every callback the integration
receives during a real session. Used to build replay fixtures for Docker E2E
tests that exercise the full push-driven pipeline against scrubbed real data.
"""

from __future__ import annotations

import json
from datetime import datetime

from pymammotion.proto import RptDevStatus

from custom_components.mammotion_lite._capture import CaptureRecorder


def test_record_writes_one_jsonl_line_with_kind_ts_and_payload(tmp_path):
    """A single record() call appends one well-formed JSONL entry.

    The entry must contain:
      - kind: the event category string passed in
      - ts:   ISO8601 UTC timestamp (with timezone) generated by the recorder
      - payload: the dict passed in, preserved exactly
    """
    trace_path = tmp_path / "capture.jsonl"
    recorder = CaptureRecorder(trace_path)

    payload = {"identifier": "Luba-VSLKJX", "params": {"foo": "bar"}}
    recorder.record("event", payload)

    raw_lines = trace_path.read_text().splitlines()
    assert len(raw_lines) == 1, f"expected exactly 1 JSONL line, got {len(raw_lines)}"

    entry = json.loads(raw_lines[0])

    assert entry["kind"] == "event"
    assert entry["payload"] == payload

    # ts must parse as an ISO8601 timestamp with timezone info attached.
    parsed_ts = datetime.fromisoformat(entry["ts"].replace("Z", "+00:00"))
    assert parsed_ts.tzinfo is not None, (
        f"ts must include timezone info, got {entry['ts']!r}"
    )


def test_record_serializes_mashumaro_object_via_to_dict(tmp_path):
    """When passed a mashumaro-style object (has .to_dict()), record() must:

      - set payload_type to the object's class name
      - set payload to the dict produced by .to_dict() (NOT the object itself,
        NOT a generic repr)

    Uses a real pymammotion proto class so we exercise the actual mashumaro
    serialisation contract - not a mock that could pass without proving the
    real object would.
    """
    trace_path = tmp_path / "capture.jsonl"
    recorder = CaptureRecorder(trace_path)

    status = RptDevStatus(battery_val=42, charge_state=1)
    expected_payload = status.to_dict()

    recorder.record("property", status)

    raw_lines = trace_path.read_text().splitlines()
    assert len(raw_lines) == 1

    entry = json.loads(raw_lines[0])
    assert entry["kind"] == "property"
    assert entry["payload_type"] == "RptDevStatus"
    assert entry["payload"] == expected_payload


def test_disabled_recorder_silently_no_ops(tmp_path):
    """CaptureRecorder(None) is a disabled recorder.

    Production callers should be able to call recorder.record(...) on every
    callback without an enabled-check. A disabled recorder must:
      - construct without raising
      - accept record() calls without raising
      - never create any file on disk
    """
    recorder = CaptureRecorder(None)

    # Multiple calls, including a mashumaro object that would normally trigger
    # serialisation, must all be silent no-ops.
    recorder.record("event", {"identifier": "Luba-VSLKJX"})
    recorder.record("property", RptDevStatus(battery_val=42))

    # Nothing should have been written anywhere under tmp_path.
    created = list(tmp_path.iterdir())
    assert created == [], f"disabled recorder created files: {created}"


def test_from_env_returns_disabled_when_var_unset(tmp_path, monkeypatch):
    """CaptureRecorder.from_env is the production entrypoint.

    When MAMMOTION_LITE_CAPTURE_DIR is unset, it must return a disabled
    recorder so that integration code can always call from_env(...) and
    record(...) unconditionally, with capture being a true opt-in.
    """
    monkeypatch.delenv("MAMMOTION_LITE_CAPTURE_DIR", raising=False)
    # Also point cwd at tmp_path so any accidental relative-path file shows up.
    monkeypatch.chdir(tmp_path)

    recorder = CaptureRecorder.from_env("Luba-VSLKJX")

    recorder.record("event", {"identifier": "Luba-VSLKJX"})
    recorder.record("property", RptDevStatus(battery_val=42))

    created = list(tmp_path.iterdir())
    assert created == [], (
        f"disabled-from-env recorder created files: {created}"
    )


def test_from_env_writes_to_dir_with_device_name_in_filename(tmp_path, monkeypatch):
    """When MAMMOTION_LITE_CAPTURE_DIR is set, from_env returns an enabled
    recorder that writes into that directory, and the filename includes the
    device_name so multiple devices on one host don't collide.
    """
    monkeypatch.setenv("MAMMOTION_LITE_CAPTURE_DIR", str(tmp_path))

    recorder = CaptureRecorder.from_env("Luba-Mini")
    recorder.record("event", {"hi": "there"})

    files = list(tmp_path.iterdir())
    assert len(files) == 1, f"expected exactly one capture file, got {files}"

    capture_file = files[0]
    assert "Luba-Mini" in capture_file.name, (
        f"capture filename should include device_name, got {capture_file.name!r}"
    )

    raw_lines = capture_file.read_text().splitlines()
    assert len(raw_lines) == 1
    entry = json.loads(raw_lines[0])
    assert entry["kind"] == "event"
    assert entry["payload"] == {"hi": "there"}


def test_from_env_creates_capture_dir_if_missing(tmp_path, monkeypatch):
    """from_env must create the capture directory if it doesn't exist yet.

    Operators will typically point MAMMOTION_LITE_CAPTURE_DIR at a fresh path
    (e.g. /config/captures/run-2026-05-13). The recorder must materialise the
    directory so the first record() doesn't trip FileNotFoundError - capture
    being best-effort means it should just work, not require pre-mkdir.
    """
    nonexistent = tmp_path / "deep" / "nested" / "captures"
    assert not nonexistent.exists()

    monkeypatch.setenv("MAMMOTION_LITE_CAPTURE_DIR", str(nonexistent))

    recorder = CaptureRecorder.from_env("Luba-Mini")
    recorder.record("event", {"hi": "there"})

    assert nonexistent.is_dir(), (
        f"from_env should have created capture dir, but {nonexistent} doesn't exist"
    )

    files = [p for p in nonexistent.iterdir() if p.is_file()]
    assert len(files) == 1, f"expected one capture file, got {files}"

    raw_lines = files[0].read_text().splitlines()
    assert len(raw_lines) == 1
    entry = json.loads(raw_lines[0])
    assert entry["kind"] == "event"
    assert entry["payload"] == {"hi": "there"}
